# Generated by Django 6.0.4 on 2026-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('Description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
