# Generated by Django 6.0.4 on 2026-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthGuide', '0002_alter_diseases_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('Description', models.TextField()),
                ('video', models.ImageField(blank=True, null=True, upload_to='video/')),
            ],
        ),
    ]
