# Generated by Django 6.0.4 on 2026-04-26 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthGuide', '0003_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv'])]),
        ),
    ]
