# Generated by Django 6.0.4 on 2026-04-26 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthGuide', '0004_alter_emergency_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'webp', 'gif'])]),
        ),
    ]
