# Generated by Django 6.0.4 on 2026-04-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthGuide', '0005_alter_diseases_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
